config/routes.rb
W3geo::Application.routes.draw do

resources :files

   devise_for :users, :controllers => { :registrations => "registrations" }
   
    get '/awaiting_confirmation',
         :to => "users#confirmation",
         :as => 'confirm_user'


   namespace :admin do
      root :to => "base#index"
      resources :users do
         resources :permissions
      end
   end

   put '/admin/users/:user_id/permissions',
   :to => 'admin/permissions#update',
   :as => :update_user_permissions


   get "users/index"
   root :to => 'customers#index'
   resources :customers do
      resources :tickets
   end


end

app/models/customer.rb
class Customer < ActiveRecord::Base
  has_many :tickets, :dependent => :delete_all
  attr_accessible :name
  validates :name, :presence => true, :uniqueness => true

  has_many :permissions, :as => :thing 

  def self.viewable_by(user)
    joins(:permissions).where(:permissions => { :action => "view", :user_id => user.id })
  end

  def self.for(user)
    user.admin? ? Customer : Customer.viewable_by(user)
  end


end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
 before_filter :authorize_admin!, :except => [:index, :show]
 before_filter :authenticate_user!, :only => [:index, :show]
 before_filter :find_customer, :only => [:show,
                                         :edit,
                                         :update,
                                         :destroy]
 def index
   @customers = Customer.for(current_user).all
 end

 def new
   @customer = Customer.new
 end

 def create
    @customer = Customer.new(params[:customer])
    if @customer.save
       flash[:notice] = "Customer has been created."
       redirect_to @customer
    else
       flash[:alert] = "Customer has not been created."
       render :action => "new"
    end
 end
 def show
 end
 def edit
 end

 def update
    if @customer.update_attributes(params[:customer])
       flash[:notice] = "Customer has been updated."
       redirect_to @customer
    else
       flash[:alert] = "Customer has not been updated."
       render :action => "edit"
    end
 end

 def destroy
    @customer.destroy 
    flash[:notice] = "Customer has been deleted."
    redirect_to  customers_path
 end





private
  def find_customer 
   @customer = Customer.for(current_user).find(params[:id])
   rescue ActiveRecord::RecordNotFound
     flash[:alert] = "The customer you were looking" +
                     " for could not be found."
     redirect_to customers_path
   end

end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/views/customers/edit.html.erb
<h2>Edit customer</h2>
<%= render "form" %>

app/views/customers/index.html.erb
<h2>Customers</h2>

<% admins_only do %>
<%= link_to "New Customer", new_customer_path %>
<% end %>
<ul>
<% @customers.each do |customer| %>
<li><%= link_to customer.name, customer %></li>
<% end %>
</ul>

app/views/customers/new.html.erb
<h2>New Customer</h2>
<%= render "form" %>

app/views/customers/show.html.erb
<% title(@customer.name,"Customer") %>
<h2><%= @customer.name %></h2>
<% admins_only do %>
<%= link_to "Edit Customer", edit_customer_path(@customer) %> | 
<%= link_to "Delete Customer",
customer_path(@customer),
:method => :delete,
:confirm => "Are you sure you want to delete this customer?" %>
<% end %>
<% authorized?("create tickets".to_sym, @customer) do %>
<%= link_to "New Ticket", new_customer_ticket_path(@customer) %>
<% end %>

<ul id='tickets'>
 <% @customer.tickets.each do |ticket| %>
  <li>
   #<%= ticket.id %> -
   <%= link_to ticket.title, [@customer, ticket] %>
  </li>
 <% end %>
</ul>